name: Java Release with Maven

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow when a tag like v1.2.3 is pushed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checks out the code from the repository

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file CalculatorApp/pom.xml  # Builds the project

    - name: Extract version from tag
      id: extract_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV  # Extracts version from the tag and stores it in an environment variable

    - name: Create GitHub release
      uses: gh-cli/gh-action@v1  # Uses GitHub CLI to create the release
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ env.VERSION }}  # Uses the extracted version number

    - name: Upload JAR as release asset
      uses: softprops/action-gh-release@v1  # This action uploads artifacts to the release
      with:
        files: CalculatorApp/target/CalculatorApp-*.jar  # Change path based on where the JAR is located after the build
        tag_name: ${{ env.VERSION }}  # Uses the extracted version for the release tag
